const std = @import("std");

pub const Operation = enum {
    none, mov, push, pop,
    xchg, in, out, xlat,
    lea, lds, les, lahf,
    sahf, pushf, popf, add,
    adc, inc, aaa, daa,
    sub, sbb, dec, neg,
    cmp, aas, das, mul,
    imul, aam, div, idiv,
    aad, cbw, cwd, not,
    shl, shr, sar, rol,
    ror, rcl, rcr, @"and",
    @"test", @"or", xor, rep,
    movs, cmps, scas, lods,
    stos, call, jmp, ret,
    je, jl, jle, jb,
    jbe, jp, jo, js,
    jne, jnl, jg, jnb,
    ja, jnp, jno, jns,
    loop, loopz, loopnz, jcxz,
    int, int3, into, iret,
    clc, cmc, stc, cld,
    std, cli, sti, hlt,
    wait, esc, lock, segment,
};
